package frc.robot.enums;

public enum AutoPosition {
    INNER, INNER_CONE, INNER_BALANCE, INNER_CONE_BALANCE, CENTER, CENTER_BALANCE, EDGE_CONE, EDGE, EDGE_BALANCE,
    EDGE_CONE_BALANCE,
    EDGE_SINGLE, EDGE_TWO, INNER_PEANUTS, NONE
}